services:
  postgres:
    image: postgres:15
    container_name: medical_postgres
    environment:
      POSTGRES_DB: medical_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medical_network

  redis:
    image: redis:7-alpine
    container_name: medical_redis
    ports:
      - "6379:6379"
    networks:
      - medical_network

  app:
    build: .
    container_name: medical_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:password@postgres:5432/medical_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    networks:
      - medical_network

volumes:
  postgres_data:

networks:
  medical_network:
    driver: bridge